### ISSUE TITLE
Update for version 241

### ISSUE THREAD

**Issue by bjrice88** [iyashpal/intellij-github-themes#1]
Absolutely love this theme but it doesn't work with version 241 IDE's yet.  Would be good to get that included, potentially just removing the upper end of the version restriction unless it stops being supported so it doesn't stop working need to be bumped every time Jetbrains releases a new version.

**Comment by iyashpal** [comment]
[github-theme.zip](https://github.com/iyashpal/intellij-github-themes/files/14391659/github-theme.zip)

@bjrice88 Can you try the above build and let me know? If it's working then I will publish the release.

**Comment by bjrice88** [comment]
Yep that works for me in the 2024 EAP for Pycharm and Webstorm.  Thanks!
