### ISSUE TITLE
Update plugin to support new version IDE

### ISSUE THREAD

**Issue by heliar-k** [iyashpal/intellij-github-themes#2]
Firstly, this is a great "github" theme for jetbrain IDE!

Jetbrain market had several similar themes, but I found that only this theme behaved consistently in several editors such as vscode neovim.

Today, when I upgraded my Pycharm to 2023.3.3, I found that this theme was incompatible with the editor version. 

So Could you please take the time to release a new version?

**Comment by iyashpal** [comment]
Latest build has been released to marketplace. OR you can download the plugin file from [here](https://github.com/iyashpal/intellij-github-themes/releases/tag/v0.0.11)
