### ISSUE TITLE
Support `targetUi="new"`

### ISSUE THREAD

**Issue by StefKors** [iyashpal/intellij-github-themes#2]
Hey! Love the github theme, would it be possible to support the new jetbrains ui?
From what I can tell this is done by editing the plugin.xml file and adding `targetUi="new"`.

See for example the rider theme pack:
`plugin.xml`: https://github.com/JetBrains/rider-theme-pack/blob/master/src/main/resources/META-INF/plugin.xml#L27

some updates might be needed to the theme json, but it seems like adding `"parentTheme": "ExperimentalDark",` should give a reasonable starting point.
`theme json`: https://github.com/JetBrains/rider-theme-pack/blob/master/src/main/resources/RiderNight.theme.json#L5C3-L5C37

Thanks again!

**Comment by iyashpal** [comment]
Hi @StefKors thank you for the findings. I have updated the attributes and published v0.0.21.
